"""Wrapper script generation for aether setup CLI."""
from __future__ import annotations

import stat
from pathlib import Path

WRAPPER_TEMPLATE = """#!/bin/bash
# Aether Agents — aether-setup wrapper
# Auto-generated by aether setup. Routes to venv console_scripts entry.

export HERMES_HOME="{hermes_home}"
exec "{venv_bin}/aether-setup" "$@"
"""


def write_aether_setup_wrapper(*, project_root: Path, venv_dir: Path, target: Path | None = None) -> Path:
    target = target or Path.home() / ".local" / "bin" / "aether-setup"
    target.parent.mkdir(parents=True, exist_ok=True)
    content = WRAPPER_TEMPLATE.format(
        hermes_home=project_root / "home",
        venv_bin=venv_dir / "bin",
    )
    existing = target.read_text() if target.exists() else ""
    if existing != content:
        target.write_text(content)
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target
