"""Regression tests for the isolated Aether setup shell contract."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SETUP = ROOT / "scripts" / "setup.sh"


def _run_bash(command: str, *, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", "-c", command],
        check=True,
        cwd=ROOT,
        env=env,
        text=True,
        capture_output=True,
    )


def test_setup_shell_is_valid_and_has_no_retired_entrypoint() -> None:
    subprocess.run(["bash", "-n", SETUP], check=True, cwd=ROOT)
    text = SETUP.read_text()
    assert "aether-setup" not in text
    assert "olympus_v3" not in text
    assert "olympus-mcp" not in text


def test_clean_python_env_removes_ambient_source_overrides() -> None:
    env = os.environ.copy()
    env["PYTHONPATH"] = "/foreign/source"
    env["HERMES_PYTHON_SRC_ROOT"] = "/foreign/hermes"
    result = _run_bash(
        f'source "{SETUP}"; clean_python_env python3 -c '
        "'import os; print(os.environ.get(\"PYTHONPATH\"), "
        "os.environ.get(\"HERMES_PYTHON_SRC_ROOT\"))'",
        env=env,
    )
    assert result.stdout.strip() == "None None"


def test_wrapper_generation_is_valid_and_idempotent(tmp_path: Path) -> None:
    fake_project = tmp_path / "project"
    fake_bin = fake_project / "home" / ".venv-hermes" / "bin" / "hermes"
    fake_bin.parent.mkdir(parents=True)
    fake_bin.write_text("#!/bin/bash\nexit 0\n")
    fake_bin.chmod(0o755)

    home = tmp_path / "home"
    home.mkdir()
    env = os.environ.copy()
    env["HOME"] = str(home)

    command = (
        f'source "{SETUP}"; '
        f'PROJECT_ROOT="{fake_project}"; '
        f'HERMES_BIN="{fake_bin}"; '
        'SCRIPT_VERSION="test"; create_wrappers'
    )
    _run_bash(command, env=env)
    _run_bash(command, env=env)

    expected = (
        "#!/bin/bash\n"
        "# Aether Agents wrapper — auto-generated by setup.sh vtest\n"
        "# Points to .venv-hermes/bin/hermes (default profile)\n\n"
        f'export HERMES_HOME="{fake_project}/home"\n'
        "unset PYTHONPATH\n"
        "unset HERMES_PYTHON_SRC_ROOT\n"
        f'exec "{fake_bin}" "$@"\n\n'
    )
    for name in ("aether", "hermes"):
        wrapper = home / ".local" / "bin" / name
        assert wrapper.read_text() == expected
        subprocess.run(["bash", "-n", wrapper], check=True)
