"""Regression tests for the isolated Aether setup shell contract."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SETUP = ROOT / "scripts" / "setup.sh"


def _run_bash(command: str, *, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", "-c", command],
        check=True,
        cwd=ROOT,
        env=env,
        text=True,
        capture_output=True,
    )


def test_setup_shell_is_valid_and_has_no_retired_entrypoint() -> None:
    subprocess.run(["bash", "-n", SETUP], check=True, cwd=ROOT)
    text = SETUP.read_text()
    assert "aether-setup" not in text
    assert "olympus_v3" not in text
    assert "olympus-mcp" not in text


def test_clean_python_env_removes_ambient_source_overrides() -> None:
    env = os.environ.copy()
    env["PYTHONPATH"] = "/foreign/source"
    env["HERMES_PYTHON_SRC_ROOT"] = "/foreign/hermes"
    result = _run_bash(
        f'source "{SETUP}"; clean_python_env python3 -c '
        "'import os; print(os.environ.get(\"PYTHONPATH\"), "
        "os.environ.get(\"HERMES_PYTHON_SRC_ROOT\"))'",
        env=env,
    )
    assert result.stdout.strip() == "None None"


def test_wrapper_generation_is_valid_and_idempotent(tmp_path: Path) -> None:
    fake_project = tmp_path / "project"
    fake_bin = fake_project / "home" / ".venv-hermes" / "bin" / "hermes"
    fake_bin.parent.mkdir(parents=True)
    fake_bin.write_text("#!/bin/bash\nexit 0\n")
    fake_bin.chmod(0o755)

    home = tmp_path / "home"
    home.mkdir()
    env = os.environ.copy()
    env["HOME"] = str(home)

    command = (
        f'source "{SETUP}"; '
        f'PROJECT_ROOT="{fake_project}"; '
        f'HERMES_BIN="{fake_bin}"; '
        'SCRIPT_VERSION="test"; create_wrappers'
    )
    _run_bash(command, env=env)
    _run_bash(command, env=env)

    expected = (
        "#!/bin/bash\n"
        "# Aether Agents wrapper — auto-generated by setup.sh vtest\n"
        "# Points to .venv-hermes/bin/hermes (default profile)\n\n"
        f'export HERMES_HOME="{fake_project}/home"\n'
        "unset PYTHONPATH\n"
        "unset HERMES_PYTHON_SRC_ROOT\n"
        f'exec "{fake_bin}" "$@"\n\n'
    )
    for name in ("aether", "hermes"):
        wrapper = home / ".local" / "bin" / name
        assert wrapper.read_text() == expected
        subprocess.run(["bash", "-n", wrapper], check=True)


def test_config_generation_includes_hermes_home_and_preserves_existing_file(tmp_path: Path) -> None:
    fake_project = tmp_path / "project"
    root_template = fake_project / "home" / "config.yaml.template"
    profile_template = fake_project / "home" / "profiles" / "hefesto" / "config.yaml.template"
    root_template.parent.mkdir(parents=True)
    profile_template.parent.mkdir(parents=True)

    template = "root: __AETHER_ROOT__\npython: __HERMES_PYTHON__\n"
    root_template.write_text(template)
    profile_template.write_text(template)

    python_path = fake_project / "home" / ".venv-hermes" / "bin" / "python"
    command = (
        f'source "{SETUP}"; '
        f'PROJECT_ROOT="{fake_project}"; '
        f'HERMES_PYTHON="{python_path}"; '
        "generate_configs"
    )
    _run_bash(command)

    expected = f"root: {fake_project}\npython: {python_path}\n"
    root_config = root_template.with_name("config.yaml")
    profile_config = profile_template.with_name("config.yaml")
    assert root_config.read_text() == expected
    assert profile_config.read_text() == expected

    root_config.write_text("preserved: true\n")
    _run_bash(command)
    assert root_config.read_text() == "preserved: true\n"


def test_makefile_prefers_candidate_local_hermes_over_path(tmp_path: Path) -> None:
    local_hermes = tmp_path / "home" / ".venv-hermes" / "bin" / "hermes"
    global_bin = tmp_path / "global-bin"
    global_hermes = global_bin / "hermes"
    local_hermes.parent.mkdir(parents=True)
    global_bin.mkdir()

    for binary in (local_hermes, global_hermes):
        binary.write_text("#!/usr/bin/env bash\nexit 0\n")
        binary.chmod(0o755)

    env = os.environ.copy()
    env["PATH"] = f"{global_bin}:{env['PATH']}"
    env["HERMES"] = "hermes"
    probe_makefile = tmp_path / "probe.mk"
    probe_makefile.write_text(
        f"include {ROOT / 'Makefile'}\n\n"
        "print-hermes:\n"
        "\t@printf '%s\\n' '$(HERMES)'\n"
    )
    result = subprocess.run(
        [
            "make",
            "--no-print-directory",
            "-C",
            str(tmp_path),
            "-f",
            str(probe_makefile),
            "print-hermes",
        ],
        check=True,
        env=env,
        text=True,
        capture_output=True,
    )

    assert result.stdout.strip() == "home/.venv-hermes/bin/hermes"


def test_make_doctor_removes_inherited_python_source_overrides(tmp_path: Path) -> None:
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    probe = """#!/usr/bin/env bash
if [ -n "${PYTHONPATH+x}" ] || [ -n "${HERMES_PYTHON_SRC_ROOT+x}" ]; then
    exit 42
fi
if [ "${1:-}" = "--version" ]; then
    echo "local-hermes"
elif [[ "${2:-}" == *"sys.version_info"* ]]; then
    echo "3.11.15"
else
    echo "✓ product-assets"
fi
"""
    fake_python = fake_bin / "python"
    fake_hermes = fake_bin / "hermes"
    for binary in (fake_python, fake_hermes):
        binary.write_text(probe)
        binary.chmod(0o755)

    env = os.environ.copy()
    env["PYTHONPATH"] = "/unrelated/hermes/source"
    env["HERMES_PYTHON_SRC_ROOT"] = "/unrelated/hermes/source"
    result = subprocess.run(
        [
            "make",
            "--no-print-directory",
            "-C",
            str(tmp_path),
            "-f",
            str(ROOT / "Makefile"),
            f"PYTHON={fake_python}",
            f"HERMES={fake_hermes}",
            "doctor",
        ],
        env=env,
        text=True,
        capture_output=True,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "local-hermes" in result.stdout
    assert "✓ product-assets" in result.stdout
