from __future__ import annotations

import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).parents[1]
CHECKER = ROOT / "scripts" / "check_documentation.py"


def _run(root: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CHECKER), "--root", str(root), *arguments],
        check=False,
        capture_output=True,
        text=True,
    )


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _registry(
    *, surfaces: list[str], status: str = "implemented", verification: str = '"tests/test_cli.py"'
) -> str:
    rendered_surfaces = ", ".join(f'"{surface}"' for surface in surfaces)
    return f'''schema_version = 1
generated_reference = "docs/reference/capabilities.md"

[[capabilities]]
id = "sample"
status = "{status}"
summary = "Sample capability."
surfaces = [{rendered_surfaces}]
documents = ["docs/current.md"]
specifications = ["specs/spec.md"]
implementation = ["src/aether_agents/cli.py"]
verification = [{verification}]
notes = ""
'''


def _derived_surfaces() -> list[str]:
    return [
        "cli.command.aether",
        "cli.command.aether.alpha",
        "cli.option.aether.--version",
        "cli.option.aether.alpha.--flag",
        "cli.argument.aether.alpha.target",
        "plugin.sample-plugin",
        "tool.sample_tool",
        "tool_action.sample_tool.status",
        "tool_action.sample_tool.validate",
        "role.morfeo",
    ]


def _repository(tmp_path: Path, *, registry: str | None = None) -> Path:
    _write(tmp_path / "src/aether_agents/__init__.py", "")
    _write(
        tmp_path / "src/aether_agents/cli.py",
        """import argparse


def _build_parser():
    parser = argparse.ArgumentParser(prog="aether")
    parser.add_argument("--version", action="store_true")
    subparsers = parser.add_subparsers(dest="command")
    alpha = subparsers.add_parser("alpha")
    alpha.add_argument("target")
    alpha.add_argument("--flag", action="store_true")
    return parser
""",
    )
    _write(
        tmp_path / "src/aether_agents/plugins/hermes_plugin.py",
        """_ACTIONS = ("status", "validate")


def register(ctx):
    ctx.register_tool(
        name="sample_tool",
        schema={
            "parameters": {
                "properties": {"action": {"enum": list(_ACTIONS)}},
            },
        },
    )
""",
    )
    _write(
        tmp_path / "pyproject.toml",
        """[project]
name = "sample"

[project.entry-points."hermes_agent.plugins"]
sample-plugin = "aether_agents.plugins.hermes_plugin"
""",
    )
    _write(tmp_path / "src/aether_agents/resources/profiles/morfeo/config.yaml", "plugins: {}\n")
    _write(tmp_path / "docs/current.md", "# Current documentation\n")
    _write(tmp_path / "specs/spec.md", "# Specification\n")
    _write(tmp_path / "tests/test_cli.py", "def test_placeholder():\n    assert True\n")
    _write(
        tmp_path / "docs/capabilities.toml",
        registry or _registry(surfaces=_derived_surfaces()),
    )
    return tmp_path


def test_write_then_check_is_deterministic_and_check_does_not_mutate(tmp_path: Path) -> None:
    root = _repository(tmp_path)

    written = _run(root, "--write")
    assert written.returncode == 0, written.stderr
    generated = root / "docs/reference/capabilities.md"
    first = generated.read_bytes()
    assert first.startswith(b"<!-- Generated by scripts/check_documentation.py; do not edit. -->\n")
    assert b"# Capability coverage\n" in first
    assert b"[capability registry](../capabilities.toml)" in first

    checked = _run(root)
    assert checked.returncode == 0, checked.stderr
    assert generated.read_bytes() == first

    rewritten = _run(root, "--write")
    assert rewritten.returncode == 0, rewritten.stderr
    assert generated.read_bytes() == first


def test_rejects_missing_derived_cli_command_and_tool_action(tmp_path: Path) -> None:
    surfaces = _derived_surfaces()
    root = _repository(
        tmp_path,
        registry=_registry(
            surfaces=[
                surface
                for surface in surfaces
                if surface not in {"cli.command.aether.alpha", "tool_action.sample_tool.validate"}
            ]
        ),
    )

    completed = _run(root, "--write")

    assert completed.returncode == 1
    assert "uncovered derived surface: cli.command.aether.alpha" in completed.stderr
    assert "uncovered derived surface: tool_action.sample_tool.validate" in completed.stderr


def test_extracts_registered_tool_actions_when_unrelated_schema_fields_are_dynamic(
    tmp_path: Path,
) -> None:
    root = _repository(tmp_path)
    plugin = root / "src/aether_agents/plugins/hermes_plugin.py"
    plugin.write_text(
        plugin.read_text(encoding="utf-8").replace(
            'schema={\n            "parameters":',
            'schema={\n            "description": describe_at_runtime(),\n            "parameters":',
        ),
        encoding="utf-8",
    )

    completed = _run(root, "--write")

    assert completed.returncode == 0, completed.stderr


def test_rejects_unsafe_or_missing_traceability_path(tmp_path: Path) -> None:
    root = _repository(tmp_path)
    registry = (root / "docs/capabilities.toml").read_text(encoding="utf-8")
    (root / "docs/capabilities.toml").write_text(
        registry.replace('"docs/current.md"', '"../outside.md"'), encoding="utf-8"
    )

    unsafe = _run(root, "--write")
    assert unsafe.returncode == 1
    assert "unsafe project-relative path" in unsafe.stderr

    (root / "docs/capabilities.toml").write_text(
        registry.replace('"docs/current.md"', '"docs/missing.md"'), encoding="utf-8"
    )
    missing = _run(root, "--write")
    assert missing.returncode == 1
    assert "missing or non-regular path: docs/missing.md" in missing.stderr


def test_rejects_a_non_regular_generated_reference_even_in_write_mode(tmp_path: Path) -> None:
    root = _repository(tmp_path)
    (root / "docs/reference/capabilities.md").mkdir(parents=True)

    completed = _run(root, "--write")

    assert completed.returncode == 1
    assert "missing or non-regular path: docs/reference/capabilities.md" in completed.stderr


def test_rejects_unknown_status_duplicate_id_and_missing_verification(tmp_path: Path) -> None:
    root = _repository(tmp_path)
    registry = (root / "docs/capabilities.toml").read_text(encoding="utf-8")
    duplicate = registry.replace('id = "sample"', 'id = "sample"', 1) + registry.replace(
        'id = "sample"', 'id = "sample"', 1
    )
    invalid = duplicate.replace('status = "implemented"', 'status = "unknown"', 1).replace(
        'verification = ["tests/test_cli.py"]', "verification = []"
    )
    (root / "docs/capabilities.toml").write_text(invalid, encoding="utf-8")

    completed = _run(root, "--write")

    assert completed.returncode == 1
    assert "unknown status: unknown" in completed.stderr
    assert "duplicate capability id: sample" in completed.stderr
    assert "implemented capability sample requires verification" in completed.stderr


def test_rejects_duplicate_and_stale_or_uncovered_surfaces(tmp_path: Path) -> None:
    root = _repository(tmp_path)
    registry = (root / "docs/capabilities.toml").read_text(encoding="utf-8")
    registry = registry.replace(
        '"tool_action.sample_tool.validate"',
        '"tool_action.sample_tool.status", "cli.command.not-real"',
    )
    (root / "docs/capabilities.toml").write_text(registry, encoding="utf-8")

    duplicate_and_uncovered = _run(root, "--write")
    assert duplicate_and_uncovered.returncode == 1
    assert "duplicate surface: tool_action.sample_tool.status" in duplicate_and_uncovered.stderr
    assert (
        "uncovered derived surface: tool_action.sample_tool.validate"
        in duplicate_and_uncovered.stderr
    )
    assert "not source-derived: cli.command.not-real" in duplicate_and_uncovered.stderr

    (root / "docs/capabilities.toml").write_text(
        registry.replace(
            '"tool_action.sample_tool.status", "cli.command.not-real"',
            '"tool_action.sample_tool.validate"',
        ),
        encoding="utf-8",
    )
    assert _run(root, "--write").returncode == 0
    generated = root / "docs/reference/capabilities.md"
    generated.write_text("stale\n", encoding="utf-8")

    stale = _run(root)
    assert stale.returncode == 1
    assert "generated reference is stale" in stale.stderr
    assert generated.read_text(encoding="utf-8") == "stale\n"


def test_policy_workflow_admits_the_documentation_inventory_and_runs_the_checker() -> None:
    workflow = (ROOT / ".github/workflows/policy.yml").read_text(encoding="utf-8")

    assert "uv run --frozen python scripts/check_documentation.py" in workflow
    assert "scripts/check_documentation.py" in workflow
    assert "tests/test_documentation.py" in workflow
    for path in (
        "docs/index.md",
        "docs/authority.md",
        "docs/getting-started.md",
        "docs/product-boundary.md",
        "docs/roles-and-authority.md",
        "docs/guides/lifecycle.md",
        "docs/guides/project-initialization.md",
        "docs/guides/objective-contracts.md",
        "docs/guides/execution.md",
        "docs/guides/observation.md",
        "docs/guides/policy-and-recovery.md",
        "docs/guides/telegram-monitor.md",
        "docs/reference/cli.md",
        "docs/reference/plugins-and-tools.md",
        "docs/reference/limitations-and-troubleshooting.md",
        "docs/reference/capabilities.md",
        "docs/capabilities.toml",
        ".aether/objective-contracts/oc_b8865f5129d60535/v1.md",
        "src/aether_agents/resources/skills/canonical-skill-governance/SKILL.md",
        "src/aether_agents/resources/skills/git-github-closeout/SKILL.md",
        "src/aether_agents/resources/skills/semver-release/SKILL.md",
    ):
        assert path in workflow
    assert "^(docs|schemas|home/(profiles|skills|plugins|prompts))/" not in workflow


def test_contribution_and_pull_request_guidance_requires_proportionate_documentation_impact() -> (
    None
):
    contributing = (ROOT / "CONTRIBUTING.md").read_text(encoding="utf-8")
    template = (ROOT / ".github/PULL_REQUEST_TEMPLATE.md").read_text(encoding="utf-8")

    assert "public or user-visible surface" in contributing
    assert "docs/capabilities.toml" in contributing
    assert "specific non-applicability rationale" in contributing
    assert "Behavior-preserving internal refactors" in contributing
    assert "Documentation / registry impact" in template
    assert "non-applicability rationale" in template


def test_canonical_skill_capabilities_are_statused_and_traceable() -> None:
    registry = tomllib.loads((ROOT / "docs/capabilities.toml").read_text(encoding="utf-8"))
    records = {record["id"]: record for record in registry["capabilities"]}

    assert records["skills.aether-canonical-resources"]["status"] == "implemented"
    assert records["skills.project-canonical-discovery"]["status"] == "implemented"
    assert (
        "lifecycle.aether-canonical-skills"
        in records["skills.aether-canonical-resources"]["surfaces"]
    )
    assert (
        "lifecycle.project-canonical-skill-discovery"
        in records["skills.project-canonical-discovery"]["surfaces"]
    )
    for skill_name in (
        "git-github-closeout",
        "semver-release",
        "canonical-skill-governance",
        "objective-contract-design",
        "supervisor-decomposition",
        "implementation-evidence",
    ):
        path = ROOT / "src" / "aether_agents" / "resources" / "skills" / skill_name / "SKILL.md"
        assert path.is_file()
        assert (
            str(path.relative_to(ROOT))
            in records["skills.aether-canonical-resources"]["implementation"]
        )
    assert ".aether/skills/<skill-name>/SKILL.md" in (ROOT / "AGENTS.md").read_text(
        encoding="utf-8"
    )


def test_stewardship_capabilities_are_distinct_and_honest() -> None:
    registry = tomllib.loads((ROOT / "docs/capabilities.toml").read_text(encoding="utf-8"))
    records = {record["id"]: record for record in registry["capabilities"]}
    expected = {
        "lifecycle.git-github-terminal-closeout": "lifecycle.git-github-terminal-closeout",
        "lifecycle.semver-release-conclusions": "lifecycle.semver-release-conclusions",
        "lifecycle.root-agents-stewardship": "lifecycle.root-agents-stewardship",
        "lifecycle.conditional-issue-intake-reconciliation": (
            "lifecycle.conditional-issue-intake-reconciliation"
        ),
    }
    traceability = {
        "lifecycle.git-github-terminal-closeout": (
            "src/aether_agents/resources/skills/git-github-closeout/SKILL.md",
            "specs/r8-workspaces-and-integration/spec.md",
        ),
        "lifecycle.semver-release-conclusions": (
            "src/aether_agents/resources/skills/semver-release/SKILL.md",
            "specs/r13-synthesis-and-release/spec.md",
        ),
        "lifecycle.root-agents-stewardship": (
            "AGENTS.md",
            "specs/r5-topology-and-isolation/spec.md",
        ),
        "lifecycle.conditional-issue-intake-reconciliation": (
            "src/aether_agents/resources/skills/git-github-closeout/SKILL.md",
            "specs/001-aether-v1-productization/spec.md",
        ),
    }

    assert set(expected) <= records.keys()
    assert set(traceability) == set(expected)
    assert {records[identifier]["status"] for identifier in expected} == {"partial"}
    assert [records[identifier]["surfaces"][0] for identifier in expected] == list(
        expected.values()
    )
    for identifier, (implementation, specification) in traceability.items():
        assert implementation in records[identifier]["implementation"]
        assert specification in records[identifier]["specifications"]
    notes = "\n".join(records[identifier]["notes"] for identifier in expected)
    for marker in (
        "prompt/skill guidance",
        "PR #299",
        "current-objective",
        "private live-profile activation",
        "public installed lifecycle",
    ):
        assert marker in notes
    assert "runtime enforcement" in notes or "runtime-enforced" in notes

    assert (
        "docs/guides/lifecycle.md" in records["lifecycle.git-github-terminal-closeout"]["documents"]
    )
    assert (
        "docs/guides/execution.md" in records["lifecycle.semver-release-conclusions"]["documents"]
    )
    assert (
        "docs/guides/project-initialization.md"
        in records["lifecycle.root-agents-stewardship"]["documents"]
    )
    assert (
        "docs/roles-and-authority.md"
        in records["lifecycle.conditional-issue-intake-reconciliation"]["documents"]
    )


def test_monitor_capability_is_registered_statused_and_traceable() -> None:
    """The Telegram Monitor surface is registered with truthful status and traceability."""

    registry = tomllib.loads((ROOT / "docs/capabilities.toml").read_text(encoding="utf-8"))
    records = {record["id"]: record for record in registry["capabilities"]}
    record = records["telegram-monitor.hourly-progress"]

    assert record["status"] == "partial"
    for surface in (
        "cli.command.aether.monitor",
        "cli.command.aether.monitor.status",
        "cli.command.aether.monitor.on",
        "cli.command.aether.monitor.off",
        "cli.command.aether.monitor.history",
        "cli.option.aether.monitor.history.--limit",
        "plugin.aether-telegram-monitor",
    ):
        assert surface in record["surfaces"], surface
    assert "docs/guides/telegram-monitor.md" in record["documents"]
    assert "specs/telegram-monitor/spec.md" in record["specifications"]
    assert "src/aether_agents/monitor/runtime.py" in record["implementation"]
    assert "scripts/qualify_telegram_monitor.py" in record["verification"]
    notes = record["notes"]
    for marker in ("remains pending", "Bot API acceptance", "not substitutes"):
        assert marker in notes, marker

    reference = (ROOT / "docs/reference/capabilities.md").read_text(encoding="utf-8")
    assert "## `telegram-monitor.hourly-progress`" in reference
    assert "**Status:** `partial`" in reference


def test_monitor_guide_documents_controls_state_and_limits() -> None:
    """The user guide carries the fixed control surface, data limits and rollback."""

    guide = (ROOT / "docs/guides/telegram-monitor.md").read_text(encoding="utf-8")

    for phrase in (
        "aether monitor status",
        "aether monitor history",
        "aether.telegram-monitor.v1",
        "aether_monitor_report_snapshot",
        "aether_monitor_reporting",
        "`0 * * * *`",
        "aether monitor off --json",
        "Bot API",
        "--live",
    ):
        assert phrase in guide or phrase.replace("`", "") in guide, phrase
    assert "thirty days" in guide
    # The guide must not promise live qualification this unit cannot evidence.
    assert "not** qualified" in guide or "not qualified" in guide


def test_policy_manifest_admits_every_monitor_path_literally() -> None:
    """Every new non-spec path is listed literally; no check or glob was widened."""

    workflow = (ROOT / ".github/workflows/policy.yml").read_text(encoding="utf-8")

    for path in (
        "docs/guides/telegram-monitor.md",
        "scripts/qualify_telegram_monitor.py",
        "src/aether_agents/monitor/__init__.py",
        "src/aether_agents/monitor/commands.py",
        "src/aether_agents/monitor/delivery.py",
        "src/aether_agents/monitor/hermes_plugin.py",
        "src/aether_agents/monitor/reporting.py",
        "src/aether_agents/monitor/runtime.py",
        "src/aether_agents/monitor/service.py",
        "src/aether_agents/monitor/sources.py",
        "src/aether_agents/monitor/store.py",
        "src/aether_agents/resources/monitor/narration-context.md",
        "src/aether_agents/resources/monitor/precheck.py",
        "tests/test_telegram_monitor_cli_plugin.py",
        "tests/test_telegram_monitor_runtime.py",
    ):
        assert path in workflow, path
    # The literal manifest stays literal: no wildcard was introduced for the new paths.
    for glob in (
        "src/aether_agents/monitor/*",
        "tests/test_telegram_monitor_*",
        "docs/guides/telegram-monitor*",
        "scripts/qualify_telegram_monitor*",
    ):
        assert glob not in workflow, glob
    assert (
        "scripts/qualify_telegram_monitor.py"
        in workflow.split("Static, format and bytecode gates")[1]
    )


def test_monitor_guide_states_what_the_store_persists_without_overclaiming() -> None:
    """Round-9 review finding: the privacy claim must match the implemented store.

    The store persists the validated narrative structure (and the narrator session
    identifier), so the guide may not claim that no narrative text is persisted.  The
    corrected wording names what is persisted and what is not (Telegram message text,
    credentials, raw transcripts, tool arguments/results, provider bindings, chat
    identifiers).
    """

    guide = (ROOT / "docs/guides/telegram-monitor.md").read_text(encoding="utf-8")
    privacy = guide.split("## State, privacy and retention")[1].split("## Failure behavior")[0]

    for phrase in (
        "validated narrative structure",
        "narrator session identifier",
        "24,000 characters",
        "Telegram message text is not persisted",
        "raw transcript",
    ):
        assert phrase in privacy, phrase
    # The audited overclaim must not survive anywhere in the guide's privacy section: the
    # store really does persist narrative prose, so the blanket sentence was false.
    assert "No credential, chat identifier, message text, raw transcript" not in privacy
