from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).parents[1]
CHECKER = ROOT / "scripts" / "check_documentation.py"


def _run(root: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CHECKER), "--root", str(root), *arguments],
        check=False,
        capture_output=True,
        text=True,
    )


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _registry(
    *, surfaces: list[str], status: str = "implemented", verification: str = '"tests/test_cli.py"'
) -> str:
    rendered_surfaces = ", ".join(f'"{surface}"' for surface in surfaces)
    return f'''schema_version = 1
generated_reference = "docs/reference/capabilities.md"

[[capabilities]]
id = "sample"
status = "{status}"
summary = "Sample capability."
surfaces = [{rendered_surfaces}]
documents = ["docs/current.md"]
specifications = ["specs/spec.md"]
implementation = ["src/aether_agents/cli.py"]
verification = [{verification}]
notes = ""
'''


def _derived_surfaces() -> list[str]:
    return [
        "cli.command.aether",
        "cli.command.aether.alpha",
        "cli.option.aether.--version",
        "cli.option.aether.alpha.--flag",
        "cli.argument.aether.alpha.target",
        "plugin.sample-plugin",
        "tool.sample_tool",
        "tool_action.sample_tool.status",
        "tool_action.sample_tool.validate",
        "role.morfeo",
    ]


def _repository(tmp_path: Path, *, registry: str | None = None) -> Path:
    _write(tmp_path / "src/aether_agents/__init__.py", "")
    _write(
        tmp_path / "src/aether_agents/cli.py",
        """import argparse


def _build_parser():
    parser = argparse.ArgumentParser(prog="aether")
    parser.add_argument("--version", action="store_true")
    subparsers = parser.add_subparsers(dest="command")
    alpha = subparsers.add_parser("alpha")
    alpha.add_argument("target")
    alpha.add_argument("--flag", action="store_true")
    return parser
""",
    )
    _write(
        tmp_path / "src/aether_agents/plugins/hermes_plugin.py",
        """_ACTIONS = ("status", "validate")


def register(ctx):
    ctx.register_tool(
        name="sample_tool",
        schema={
            "parameters": {
                "properties": {"action": {"enum": list(_ACTIONS)}},
            },
        },
    )
""",
    )
    _write(
        tmp_path / "pyproject.toml",
        """[project]
name = "sample"

[project.entry-points."hermes_agent.plugins"]
sample-plugin = "aether_agents.plugins.hermes_plugin"
""",
    )
    _write(tmp_path / "src/aether_agents/resources/profiles/morfeo/config.yaml", "plugins: {}\n")
    _write(tmp_path / "docs/current.md", "# Current documentation\n")
    _write(tmp_path / "specs/spec.md", "# Specification\n")
    _write(tmp_path / "tests/test_cli.py", "def test_placeholder():\n    assert True\n")
    _write(
        tmp_path / "docs/capabilities.toml",
        registry or _registry(surfaces=_derived_surfaces()),
    )
    return tmp_path


def test_write_then_check_is_deterministic_and_check_does_not_mutate(tmp_path: Path) -> None:
    root = _repository(tmp_path)

    written = _run(root, "--write")
    assert written.returncode == 0, written.stderr
    generated = root / "docs/reference/capabilities.md"
    first = generated.read_bytes()
    assert first.startswith(b"<!-- Generated by scripts/check_documentation.py; do not edit. -->\n")
    assert b"# Capability coverage\n" in first
    assert b"[capability registry](../capabilities.toml)" in first

    checked = _run(root)
    assert checked.returncode == 0, checked.stderr
    assert generated.read_bytes() == first

    rewritten = _run(root, "--write")
    assert rewritten.returncode == 0, rewritten.stderr
    assert generated.read_bytes() == first


def test_rejects_missing_derived_cli_command_and_tool_action(tmp_path: Path) -> None:
    surfaces = _derived_surfaces()
    root = _repository(
        tmp_path,
        registry=_registry(
            surfaces=[
                surface
                for surface in surfaces
                if surface not in {"cli.command.aether.alpha", "tool_action.sample_tool.validate"}
            ]
        ),
    )

    completed = _run(root, "--write")

    assert completed.returncode == 1
    assert "uncovered derived surface: cli.command.aether.alpha" in completed.stderr
    assert "uncovered derived surface: tool_action.sample_tool.validate" in completed.stderr


def test_extracts_registered_tool_actions_when_unrelated_schema_fields_are_dynamic(
    tmp_path: Path,
) -> None:
    root = _repository(tmp_path)
    plugin = root / "src/aether_agents/plugins/hermes_plugin.py"
    plugin.write_text(
        plugin.read_text(encoding="utf-8").replace(
            'schema={\n            "parameters":',
            'schema={\n            "description": describe_at_runtime(),\n            "parameters":',
        ),
        encoding="utf-8",
    )

    completed = _run(root, "--write")

    assert completed.returncode == 0, completed.stderr


def test_rejects_unsafe_or_missing_traceability_path(tmp_path: Path) -> None:
    root = _repository(tmp_path)
    registry = (root / "docs/capabilities.toml").read_text(encoding="utf-8")
    (root / "docs/capabilities.toml").write_text(
        registry.replace('"docs/current.md"', '"../outside.md"'), encoding="utf-8"
    )

    unsafe = _run(root, "--write")
    assert unsafe.returncode == 1
    assert "unsafe project-relative path" in unsafe.stderr

    (root / "docs/capabilities.toml").write_text(
        registry.replace('"docs/current.md"', '"docs/missing.md"'), encoding="utf-8"
    )
    missing = _run(root, "--write")
    assert missing.returncode == 1
    assert "missing or non-regular path: docs/missing.md" in missing.stderr


def test_rejects_a_non_regular_generated_reference_even_in_write_mode(tmp_path: Path) -> None:
    root = _repository(tmp_path)
    (root / "docs/reference/capabilities.md").mkdir(parents=True)

    completed = _run(root, "--write")

    assert completed.returncode == 1
    assert "missing or non-regular path: docs/reference/capabilities.md" in completed.stderr


def test_rejects_unknown_status_duplicate_id_and_missing_verification(tmp_path: Path) -> None:
    root = _repository(tmp_path)
    registry = (root / "docs/capabilities.toml").read_text(encoding="utf-8")
    duplicate = registry.replace('id = "sample"', 'id = "sample"', 1) + registry.replace(
        'id = "sample"', 'id = "sample"', 1
    )
    invalid = duplicate.replace('status = "implemented"', 'status = "unknown"', 1).replace(
        'verification = ["tests/test_cli.py"]', "verification = []"
    )
    (root / "docs/capabilities.toml").write_text(invalid, encoding="utf-8")

    completed = _run(root, "--write")

    assert completed.returncode == 1
    assert "unknown status: unknown" in completed.stderr
    assert "duplicate capability id: sample" in completed.stderr
    assert "implemented capability sample requires verification" in completed.stderr


def test_rejects_duplicate_and_stale_or_uncovered_surfaces(tmp_path: Path) -> None:
    root = _repository(tmp_path)
    registry = (root / "docs/capabilities.toml").read_text(encoding="utf-8")
    registry = registry.replace(
        '"tool_action.sample_tool.validate"',
        '"tool_action.sample_tool.status", "cli.command.not-real"',
    )
    (root / "docs/capabilities.toml").write_text(registry, encoding="utf-8")

    duplicate_and_uncovered = _run(root, "--write")
    assert duplicate_and_uncovered.returncode == 1
    assert "duplicate surface: tool_action.sample_tool.status" in duplicate_and_uncovered.stderr
    assert (
        "uncovered derived surface: tool_action.sample_tool.validate"
        in duplicate_and_uncovered.stderr
    )
    assert "not source-derived: cli.command.not-real" in duplicate_and_uncovered.stderr

    (root / "docs/capabilities.toml").write_text(
        registry.replace(
            '"tool_action.sample_tool.status", "cli.command.not-real"',
            '"tool_action.sample_tool.validate"',
        ),
        encoding="utf-8",
    )
    assert _run(root, "--write").returncode == 0
    generated = root / "docs/reference/capabilities.md"
    generated.write_text("stale\n", encoding="utf-8")

    stale = _run(root)
    assert stale.returncode == 1
    assert "generated reference is stale" in stale.stderr
    assert generated.read_text(encoding="utf-8") == "stale\n"


def test_policy_workflow_admits_the_documentation_inventory_and_runs_the_checker() -> None:
    workflow = (ROOT / ".github/workflows/policy.yml").read_text(encoding="utf-8")

    assert "uv run --frozen python scripts/check_documentation.py" in workflow
    assert "scripts/check_documentation.py" in workflow
    assert "tests/test_documentation.py" in workflow
    for path in (
        "docs/index.md",
        "docs/authority.md",
        "docs/getting-started.md",
        "docs/product-boundary.md",
        "docs/roles-and-authority.md",
        "docs/guides/lifecycle.md",
        "docs/guides/project-initialization.md",
        "docs/guides/objective-contracts.md",
        "docs/guides/execution.md",
        "docs/guides/observation.md",
        "docs/guides/policy-and-recovery.md",
        "docs/reference/cli.md",
        "docs/reference/plugins-and-tools.md",
        "docs/reference/limitations-and-troubleshooting.md",
        "docs/reference/capabilities.md",
        "docs/capabilities.toml",
        ".aether/objective-contracts/oc_a28ff9b7fa20d29d/v1.md",
        ".aether/objective-contracts/oc_b8865f5129d60535/v1.md",
        "src/aether_agents/resources/skills/canonical-skill-governance/SKILL.md",
        "src/aether_agents/resources/skills/git-github-closeout/SKILL.md",
        "src/aether_agents/resources/skills/semver-release/SKILL.md",
    ):
        assert path in workflow
    assert "^(docs|schemas|home/(profiles|skills|plugins|prompts))/" not in workflow


def test_contribution_and_pull_request_guidance_requires_proportionate_documentation_impact() -> (
    None
):
    contributing = (ROOT / "CONTRIBUTING.md").read_text(encoding="utf-8")
    template = (ROOT / ".github/PULL_REQUEST_TEMPLATE.md").read_text(encoding="utf-8")

    assert "public or user-visible surface" in contributing
    assert "docs/capabilities.toml" in contributing
    assert "specific non-applicability rationale" in contributing
    assert "Behavior-preserving internal refactors" in contributing
    assert "Documentation / registry impact" in template
    assert "non-applicability rationale" in template


def test_canonical_skill_capabilities_are_statused_and_traceable() -> None:
    registry = tomllib.loads((ROOT / "docs/capabilities.toml").read_text(encoding="utf-8"))
    records = {record["id"]: record for record in registry["capabilities"]}

    assert records["skills.aether-canonical-resources"]["status"] == "implemented"
    assert records["skills.project-canonical-discovery"]["status"] == "implemented"
    assert (
        "lifecycle.aether-canonical-skills"
        in records["skills.aether-canonical-resources"]["surfaces"]
    )
    assert (
        "lifecycle.project-canonical-skill-discovery"
        in records["skills.project-canonical-discovery"]["surfaces"]
    )
    assert "Ten Aether Canonical Skills" in records["skills.aether-canonical-resources"]["summary"]
    packaged_skill_paths = {
        str(path.relative_to(ROOT))
        for path in (ROOT / "src" / "aether_agents" / "resources" / "skills").glob("*/SKILL.md")
    }
    assert len(packaged_skill_paths) == 10
    registered_skill_paths = {
        path
        for path in records["skills.aether-canonical-resources"]["implementation"]
        if path.endswith("/SKILL.md")
    }
    assert registered_skill_paths == packaged_skill_paths
    for skill_path in packaged_skill_paths:
        assert (ROOT / skill_path).is_file()
    assert ".aether/skills/<skill-name>/SKILL.md" in (ROOT / "AGENTS.md").read_text(
        encoding="utf-8"
    )


def test_stewardship_capabilities_are_distinct_and_honest() -> None:
    registry = tomllib.loads((ROOT / "docs/capabilities.toml").read_text(encoding="utf-8"))
    records = {record["id"]: record for record in registry["capabilities"]}
    expected = {
        "lifecycle.git-github-terminal-closeout": "lifecycle.git-github-terminal-closeout",
        "lifecycle.semver-release-conclusions": "lifecycle.semver-release-conclusions",
        "lifecycle.root-agents-stewardship": "lifecycle.root-agents-stewardship",
        "lifecycle.conditional-issue-intake-reconciliation": (
            "lifecycle.conditional-issue-intake-reconciliation"
        ),
    }
    traceability = {
        "lifecycle.git-github-terminal-closeout": (
            "src/aether_agents/resources/skills/git-github-closeout/SKILL.md",
            "specs/r8-workspaces-and-integration/spec.md",
        ),
        "lifecycle.semver-release-conclusions": (
            "src/aether_agents/resources/skills/semver-release/SKILL.md",
            "specs/r13-synthesis-and-release/spec.md",
        ),
        "lifecycle.root-agents-stewardship": (
            "AGENTS.md",
            "specs/r5-topology-and-isolation/spec.md",
        ),
        "lifecycle.conditional-issue-intake-reconciliation": (
            "src/aether_agents/resources/skills/git-github-closeout/SKILL.md",
            "specs/001-aether-v1-productization/spec.md",
        ),
    }

    assert set(expected) <= records.keys()
    assert set(traceability) == set(expected)
    assert {records[identifier]["status"] for identifier in expected} == {"partial"}
    assert [records[identifier]["surfaces"][0] for identifier in expected] == list(
        expected.values()
    )
    for identifier, (implementation, specification) in traceability.items():
        assert implementation in records[identifier]["implementation"]
        assert specification in records[identifier]["specifications"]
    notes = "\n".join(records[identifier]["notes"] for identifier in expected)
    for marker in (
        "prompt/skill guidance",
        "PR #299",
        "current-objective",
        "private live-profile activation",
        "public installed lifecycle",
    ):
        assert marker in notes
    assert "runtime enforcement" in notes or "runtime-enforced" in notes

    assert (
        "docs/guides/lifecycle.md" in records["lifecycle.git-github-terminal-closeout"]["documents"]
    )
    assert (
        "docs/guides/execution.md" in records["lifecycle.semver-release-conclusions"]["documents"]
    )
    assert (
        "docs/guides/project-initialization.md"
        in records["lifecycle.root-agents-stewardship"]["documents"]
    )
    assert (
        "docs/roles-and-authority.md"
        in records["lifecycle.conditional-issue-intake-reconciliation"]["documents"]
    )


def test_retired_surfaces_are_absent_from_current_registry_and_guidance() -> None:
    registry_text = (ROOT / "docs/capabilities.toml").read_text(encoding="utf-8")
    registry = tomllib.loads(registry_text)
    records = {record["id"]: record for record in registry["capabilities"]}
    surfaces = {surface for record in records.values() for surface in record["surfaces"]}

    assert "lifecycle.qualification-laboratory" not in records
    assert "telegram-monitor.hourly-progress" not in records
    assert "lifecycle.qualification-laboratory" not in surfaces
    assert "cli.command.aether.monitor" not in surfaces
    assert "plugin.aether-telegram-monitor" not in surfaces
    assert not (ROOT / "docs/guides/telegram-monitor.md").exists()
    assert (ROOT / "specs/telegram-monitor/spec.md").is_file()
    assert (ROOT / "specs/lab-monitor-retirement/spec.md").is_file()
    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert "Hermes-native cron, ordinary Telegram interaction" in readme
    assert "native task/final/input notifications remain unchanged" in readme

    documents = {
        "README.md": ("docs/guides/telegram-monitor.md", "aether monitor"),
        "docs/index.md": ("guides/telegram-monitor.md",),
        "docs/getting-started.md": (
            "aether monitor",
            "qualify_telegram_monitor.py",
            "guides/telegram-monitor.md",
        ),
        "docs/guides/observation.md": ("aether_agents.lab", "scripts/e2e/"),
        "docs/product-boundary.md": ("aether-telegram-monitor", "qualification laboratory"),
        "docs/reference/cli.md": ("aether monitor", "qualify_telegram_monitor.py"),
        "docs/reference/plugins-and-tools.md": (
            "aether-telegram-monitor",
            "aether_monitor",
            "aether_monitor_report_snapshot",
        ),
        "docs/guides/morfeo-tool-configuration.md": ("aether_monitor",),
    }
    for path, retired_markers in documents.items():
        text = (ROOT / path).read_text(encoding="utf-8").lower()
        for marker in retired_markers:
            assert marker.lower() not in text, f"{path} retains current retired surface {marker!r}"


def test_policy_manifest_tracks_retirement_without_widening_ci_gates() -> None:
    workflow = (ROOT / ".github/workflows/policy.yml").read_text(encoding="utf-8")

    assert "tests/runtime_isolation.py" in workflow
    for path in (
        "docs/guides/telegram-monitor.md",
        "lab/README.md",
        "scripts/e2e/README.md",
        "scripts/qualify_telegram_monitor.py",
        "scripts/telegram_monitor_lab.py",
        "src/aether_agents/lab/__init__.py",
        "src/aether_agents/monitor/__init__.py",
        "src/aether_agents/resources/lab",
        "src/aether_agents/resources/monitor/precheck.py",
        "tests/fixtures/e2e",
        "tests/test_e2e_harness.py",
        "tests/test_e2e15_qualification.py",
        "tests/test_lab_formalization.py",
        "tests/test_telegram_monitor_cli_plugin.py",
    ):
        assert path not in workflow, path
    assert "tests/test_e2e_matrix.py" in workflow
    # The literal manifest stays literal: no wildcard was introduced for deleted paths.
    for glob in (
        "lab/**",
        "scripts/e2e/**",
        "src/aether_agents/lab/**",
        "src/aether_agents/monitor/*",
        "tests/test_lab*",
        "tests/test_telegram_monitor_*",
        "docs/guides/telegram-monitor*",
        "scripts/qualify_telegram_monitor*",
    ):
        assert glob not in workflow, glob
    static_gate = workflow.split("Static, format and bytecode gates")[1]
    assert "python -m compileall -q src tests scripts" in static_gate
    assert "ruff check src/aether_agents tests scripts" in static_gate
    assert "ruff format --check src/aether_agents tests scripts" in static_gate


SEMANTIC_MAINTENANCE_SURFACES = (
    "specs/005-project-knowledge-graphify/contracts/expanded-tools-and-semantic.md",
    "specs/005-project-knowledge-graphify/spec.md",
    "docs/guides/project-knowledge.md",
    "docs/reference/plugins-and-tools.md",
    "docs/reference/cli.md",
    "docs/reference/limitations-and-troubleshooting.md",
    "docs/capabilities.toml",
    "src/aether_agents/resources/skills/project-knowledge/SKILL.md",
)


def test_semantic_maintenance_documentation_states_the_corrected_transaction() -> None:
    """Semantic user-facing text owns the corrected transaction, never the withdrawn design.

    The stage-005 semantic correction replaced the fragment-merge application path and the
    600-second invocation deadline with an additive overlay and one 300-second total budget.
    These surfaces are the place a reader learns that behavior, so a re-asserted withdrawal
    or an unstated bound is a documentation defect rather than a wording preference.
    """

    texts = {
        path: (ROOT / path).read_text(encoding="utf-8") for path in SEMANTIC_MAINTENANCE_SURFACES
    }

    for path, text in texts.items():
        for match in re.finditer(r"(?i)600[-\s]seconds?", text):
            window = text[max(0, match.start() - 200) : match.end() + 200].lower()
            assert "withdraw" in window, f"{path} re-asserts the retired 600-second bound"
        for line in text.splitlines():
            if "build_merge" in line:
                assert re.search(r"(?i)\b(never|not|no|without)\b", line), (
                    f"{path} presents the global merge path outside a prohibition"
                )
        assert "/home/" not in text

    for path in (
        "specs/005-project-knowledge-graphify/contracts/expanded-tools-and-semantic.md",
        "specs/005-project-knowledge-graphify/spec.md",
        "docs/guides/project-knowledge.md",
        "docs/reference/plugins-and-tools.md",
        "docs/reference/cli.md",
        "docs/capabilities.toml",
        "src/aether_agents/resources/skills/project-knowledge/SKILL.md",
    ):
        assert "300-second" in texts[path], path

    contract = texts[
        "specs/005-project-knowledge-graphify/contracts/expanded-tools-and-semantic.md"
    ]
    for marker in (
        "additive overlay",
        "origin=llm",
        "structural projection",
        "fail-closed",
        "not served as a trusted semantic result",
    ):
        assert marker in contract, marker

    guide = texts["docs/guides/project-knowledge.md"]
    for marker in ("semantic_trusted", "semantic_pending", "origin=llm", "legacy"):
        assert marker in guide, marker

    skill = texts["src/aether_agents/resources/skills/project-knowledge/SKILL.md"]
    for marker in ("300-second", "origin=llm", "never a global graph merge", "legacy/structural"):
        assert marker in skill, marker

    registry = tomllib.loads(texts["docs/capabilities.toml"])
    record = {row["id"]: row for row in registry["capabilities"]}["knowledge.shared-project-graph"]
    for marker in ("300-second", "origin=llm", "route-qualified", "snapshot state"):
        assert marker in record["notes"], marker
    assert "tests/test_knowledge_semantic_manager.py" in record["verification"]
