#!/usr/bin/env python3
"""Validate and render Aether's as-built capability documentation registry."""

from __future__ import annotations

import argparse
import ast
import importlib
import posixpath
import re
import sys
import tomllib
from pathlib import Path, PurePosixPath
from typing import Any, Iterable, Sequence, cast

DEFAULT_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = "docs/capabilities.toml"
GENERATED_HEADER = "<!-- Generated by scripts/check_documentation.py; do not edit. -->"
REQUIRED_FIELDS = (
    "id",
    "status",
    "summary",
    "surfaces",
    "documents",
    "specifications",
    "implementation",
    "verification",
    "notes",
)
STATUSES = frozenset({"implemented", "partial", "unsupported", "transitional", "deprecated"})
SURFACE_PREFIXES = (
    "cli.command.",
    "cli.option.",
    "cli.argument.",
    "plugin.",
    "tool.",
    "tool_action.",
    "role.",
    "policy.",
    "lifecycle.",
)
DERIVED_PREFIXES = SURFACE_PREFIXES[:7]
CAPABILITY_ID = re.compile(r"^[a-z0-9]+(?:[.-][a-z0-9]+)*$")
SAFE_PATH = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]*$")


class DocumentationValidationError(ValueError):
    """A collection of stable documentation-validation failures."""

    def __init__(self, errors: Iterable[str]) -> None:
        self.errors = tuple(sorted(set(errors)))
        super().__init__("; ".join(self.errors))


def _safe_relative_path(root: Path, raw: object, errors: list[str]) -> Path | None:
    if not isinstance(raw, str) or not raw or not SAFE_PATH.fullmatch(raw):
        errors.append(f"unsafe project-relative path: {raw!r}")
        return None
    pure = PurePosixPath(raw)
    if pure.is_absolute() or any(part in {"", ".", ".."} for part in pure.parts):
        errors.append(f"unsafe project-relative path: {raw}")
        return None
    candidate = root.joinpath(*pure.parts)
    ancestor = root
    for index, part in enumerate(pure.parts):
        ancestor = ancestor / part
        if ancestor.is_symlink():
            errors.append(f"unsafe symbolic-link path: {raw}")
            return None
        if index < len(pure.parts) - 1 and ancestor.exists() and not ancestor.is_dir():
            errors.append(f"unsafe non-directory ancestor: {raw}")
            return None
    return candidate


def _validate_file_path(
    root: Path,
    raw: object,
    errors: list[str],
    *,
    allow_missing: bool = False,
) -> None:
    candidate = _safe_relative_path(root, raw, errors)
    if candidate is None or allow_missing:
        return
    if not candidate.is_file() or candidate.is_symlink():
        errors.append(f"missing or non-regular path: {raw}")


def _string_list(record: dict[str, Any], field: str, errors: list[str]) -> list[str]:
    value = record.get(field)
    if not isinstance(value, list) or not all(isinstance(item, str) and item for item in value):
        errors.append(f"capability {record.get('id', '<unknown>')!r} has invalid {field}")
        return []
    return value


def _load_registry(root: Path) -> tuple[dict[str, Any] | None, list[str]]:
    errors: list[str] = []
    path = root / REGISTRY_PATH
    if path.is_symlink() or not path.is_file():
        return None, [f"missing or non-regular registry: {REGISTRY_PATH}"]
    try:
        with path.open("rb") as stream:
            loaded = tomllib.load(stream)
    except (OSError, tomllib.TOMLDecodeError) as error:
        return None, [f"registry is unreadable: {error}"]
    if not isinstance(loaded, dict):
        return None, ["registry root must be a TOML table"]
    if loaded.get("schema_version") != 1:
        errors.append("registry schema_version must be 1")
    if loaded.get("generated_reference") != "docs/reference/capabilities.md":
        errors.append("registry generated_reference must be docs/reference/capabilities.md")
    records = loaded.get("capabilities")
    if not isinstance(records, list) or not records:
        errors.append("registry must define at least one capability")
    return loaded, errors


def _extract_cli_surfaces(root: Path) -> set[str]:
    source_root = root / "src"
    if not source_root.is_dir():
        raise RuntimeError("missing source directory: src")
    sys.path.insert(0, str(source_root))
    try:
        importlib.invalidate_caches()
        module = importlib.import_module("aether_agents.cli")
        build_parser = getattr(module, "_build_parser", None)
        if not callable(build_parser):
            raise RuntimeError("aether_agents.cli does not expose _build_parser")
        parser = build_parser()
    except Exception as error:
        raise RuntimeError(f"could not safely construct Aether CLI parser: {error}") from error
    finally:
        sys.path.pop(0)

    surfaces: set[str] = set()

    def visit(current: argparse.ArgumentParser, command_path: str) -> None:
        surfaces.add(f"cli.command.{command_path}")
        for action in current._actions:
            if isinstance(action, argparse._HelpAction):
                continue
            if isinstance(action, argparse._SubParsersAction):
                for name, child in sorted(action.choices.items()):
                    visit(cast(argparse.ArgumentParser, child), f"{command_path}.{name}")
                continue
            if action.option_strings:
                for option in action.option_strings:
                    if option not in {"-h", "--help"}:
                        surfaces.add(f"cli.option.{command_path}.{option}")
            elif action.dest is not argparse.SUPPRESS:
                surfaces.add(f"cli.argument.{command_path}.{action.dest}")

    visit(parser, "aether")
    return surfaces


def _literal_value(
    node: ast.AST, names: dict[str, ast.AST], resolving: set[str] | None = None
) -> Any:
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.Name):
        resolving = resolving or set()
        if node.id in resolving or node.id not in names:
            raise ValueError(f"unresolved name: {node.id}")
        return _literal_value(names[node.id], names, resolving | {node.id})
    if isinstance(node, (ast.List, ast.Tuple, ast.Set)):
        return [_literal_value(item, names, resolving) for item in node.elts]
    if isinstance(node, ast.Dict):
        result: dict[Any, Any] = {}
        for key, value in zip(node.keys, node.values, strict=True):
            if key is None:
                raise ValueError("dictionary unpacking is not a literal")
            result[_literal_value(key, names, resolving)] = _literal_value(value, names, resolving)
        return result
    if (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Name)
        and node.func.id in {"list", "tuple"}
    ):
        if len(node.args) != 1 or node.keywords:
            raise ValueError("unsupported literal constructor")
        value = _literal_value(node.args[0], names, resolving)
        return list(value)
    raise ValueError(f"unsupported literal expression: {type(node).__name__}")


def _module_literals(tree: ast.Module) -> dict[str, ast.AST]:
    literals: dict[str, ast.AST] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    literals[target.id] = node.value
        elif (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.value is not None
        ):
            literals[node.target.id] = node.value
    return literals


def _resolve_literal_node(
    node: ast.AST,
    names: dict[str, ast.AST],
    resolving: set[str] | None = None,
) -> ast.AST:
    if not isinstance(node, ast.Name):
        return node
    resolving = resolving or set()
    if node.id in resolving or node.id not in names:
        raise ValueError(f"unresolved name: {node.id}")
    return _resolve_literal_node(names[node.id], names, resolving | {node.id})


def _literal_mapping_value(node: ast.AST, key: str, names: dict[str, ast.AST]) -> ast.AST | None:
    resolved = _resolve_literal_node(node, names)
    if not isinstance(resolved, ast.Dict):
        return None
    for candidate, value in zip(resolved.keys, resolved.values, strict=True):
        if isinstance(candidate, ast.Constant) and candidate.value == key:
            return value
    return None


def _tool_actions(schema: ast.AST, names: dict[str, ast.AST]) -> list[str]:
    """Read only the action enum so dynamic descriptive schema fields stay irrelevant."""
    try:
        parameters = _literal_mapping_value(schema, "parameters", names)
        properties = (
            _literal_mapping_value(parameters, "properties", names)
            if parameters is not None
            else None
        )
        action = (
            _literal_mapping_value(properties, "action", names) if properties is not None else None
        )
        enum = _literal_mapping_value(action, "enum", names) if action is not None else None
        values = _literal_value(enum, names) if enum is not None else None
    except ValueError:
        return []
    return (
        values
        if isinstance(values, list) and all(isinstance(value, str) for value in values)
        else []
    )


def _registered_tool_calls(tree: ast.AST) -> Iterable[ast.Call]:
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        function = node.func
        if (isinstance(function, ast.Attribute) and function.attr == "register_tool") or (
            isinstance(function, ast.Name) and function.id == "register_tool"
        ):
            yield node


def _extract_tool_surfaces(root: Path) -> set[str]:
    source_root = root / "src" / "aether_agents"
    if not source_root.is_dir():
        raise RuntimeError("missing Aether source package")
    surfaces: set[str] = set()
    for path in sorted(source_root.rglob("*.py")):
        if path.is_symlink():
            raise RuntimeError(f"unsafe symbolic-link source: {path.relative_to(root)}")
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except (OSError, UnicodeError, SyntaxError) as error:
            raise RuntimeError(
                f"could not parse source for tool extraction: {path}: {error}"
            ) from error
        literals = _module_literals(tree)
        for call in _registered_tool_calls(tree):
            keywords = {
                keyword.arg: keyword.value for keyword in call.keywords if keyword.arg is not None
            }
            try:
                name = _literal_value(keywords["name"], literals)
            except (KeyError, ValueError):
                continue
            schema = keywords.get("schema")
            if not isinstance(name, str) or schema is None:
                continue
            surfaces.add(f"tool.{name}")
            surfaces.update(
                f"tool_action.{name}.{action}" for action in _tool_actions(schema, literals)
            )
    return surfaces


def _extract_plugin_surfaces(root: Path) -> set[str]:
    pyproject = root / "pyproject.toml"
    if pyproject.is_symlink() or not pyproject.is_file():
        raise RuntimeError("missing or non-regular pyproject.toml")
    try:
        with pyproject.open("rb") as stream:
            project = tomllib.load(stream)
        entries = project["project"]["entry-points"]["hermes_agent.plugins"]
    except (KeyError, OSError, tomllib.TOMLDecodeError, TypeError) as error:
        raise RuntimeError(f"could not extract Hermes plugin entry points: {error}") from error
    if not isinstance(entries, dict) or not all(isinstance(name, str) for name in entries):
        raise RuntimeError("Hermes plugin entry points must be a string-keyed table")
    return {f"plugin.{name}" for name in entries}


def _extract_role_surfaces(root: Path) -> set[str]:
    profiles = root / "src" / "aether_agents" / "resources" / "profiles"
    if profiles.is_symlink() or not profiles.is_dir():
        raise RuntimeError("missing or unsafe portable profile resources")
    surfaces = {
        f"role.{path.name}"
        for path in profiles.iterdir()
        if path.is_dir() and not path.is_symlink() and (path / "config.yaml").is_file()
    }
    if not surfaces:
        raise RuntimeError("no portable role resources with config.yaml were found")
    return surfaces


def _derived_surfaces(root: Path) -> set[str]:
    return (
        _extract_cli_surfaces(root)
        | _extract_plugin_surfaces(root)
        | _extract_tool_surfaces(root)
        | _extract_role_surfaces(root)
    )


def _validate_registry(
    root: Path,
    registry: dict[str, Any],
    *,
    allow_generated_reference_missing: bool,
) -> tuple[list[dict[str, Any]], list[str]]:
    errors: list[str] = []
    reference = registry.get("generated_reference")
    reference_path = _safe_relative_path(root, reference, errors)
    if reference_path is not None:
        if reference_path.is_symlink() or (
            reference_path.exists() and not reference_path.is_file()
        ):
            errors.append(f"missing or non-regular path: {reference}")
        elif not allow_generated_reference_missing and not reference_path.is_file():
            errors.append(f"missing or non-regular path: {reference}")

    records = registry.get("capabilities")
    if not isinstance(records, list):
        return [], errors
    validated: list[dict[str, Any]] = []
    ids: set[str] = set()
    surfaces: set[str] = set()
    for raw_record in records:
        if not isinstance(raw_record, dict):
            errors.append("capability record must be a TOML table")
            continue
        record = dict(raw_record)
        for field in REQUIRED_FIELDS:
            if field not in record:
                errors.append(f"capability {record.get('id', '<unknown>')!r} is missing {field}")
        identifier = record.get("id")
        if not isinstance(identifier, str) or not CAPABILITY_ID.fullmatch(identifier):
            errors.append(f"invalid capability id: {identifier!r}")
        elif identifier in ids:
            errors.append(f"duplicate capability id: {identifier}")
        else:
            ids.add(identifier)
        status = record.get("status")
        if status not in STATUSES:
            errors.append(f"unknown status: {status}")
        summary = record.get("summary")
        if not isinstance(summary, str) or not summary.strip():
            errors.append(f"capability {identifier!r} requires a non-empty summary")
        notes = record.get("notes")
        if not isinstance(notes, str):
            errors.append(f"capability {identifier!r} has invalid notes")
        elif status != "implemented" and not notes.strip():
            errors.append(f"{status} capability {identifier} requires notes")

        record_surfaces = _string_list(record, "surfaces", errors)
        for surface in record_surfaces:
            if not surface.startswith(SURFACE_PREFIXES):
                errors.append(f"invalid surface prefix: {surface}")
            if surface in surfaces:
                errors.append(f"duplicate surface: {surface}")
            else:
                surfaces.add(surface)

        fields = {
            field: _string_list(record, field, errors)
            for field in ("documents", "specifications", "implementation", "verification")
        }
        if not fields["documents"]:
            errors.append(f"capability {identifier!r} requires current documentation")
        if status in {"implemented", "partial", "transitional"}:
            for field in ("implementation", "verification"):
                if not fields[field]:
                    errors.append(f"{status} capability {identifier} requires {field}")
        for values in fields.values():
            for path in values:
                _validate_file_path(
                    root,
                    path,
                    errors,
                    allow_missing=allow_generated_reference_missing and path == reference,
                )
        validated.append(record)

    try:
        derived = _derived_surfaces(root)
    except RuntimeError as error:
        errors.append(str(error))
        derived = set()
    for surface in sorted(derived - surfaces):
        errors.append(f"uncovered derived surface: {surface}")
    for surface in sorted(surfaces):
        if surface.startswith(DERIVED_PREFIXES) and surface not in derived:
            errors.append(f"derived surface is not source-derived: {surface}")
    return validated, errors


def _link_from_reference(path: str) -> str:
    destination = posixpath.relpath(path, start="docs/reference")
    return f"[{path}]({destination})"


def _render_paths(paths: list[str]) -> list[str]:
    return [f"- {_link_from_reference(path)}" for path in sorted(paths)] or ["- None."]


def render(records: Sequence[dict[str, Any]]) -> str:
    """Render the canonical, deterministic coverage report from a validated registry."""
    lines = [
        GENERATED_HEADER,
        "# Capability coverage",
        "",
        "This reference is generated from the [capability registry](../capabilities.toml).",
    ]
    for record in sorted(records, key=lambda item: str(item["id"])):
        lines.extend(
            [
                "",
                f"## `{record['id']}`",
                "",
                f"**Status:** `{record['status']}`",
                "",
                record["summary"],
                "",
                "### Surfaces",
            ]
        )
        lines.extend(f"- `{surface}`" for surface in sorted(record["surfaces"]))
        if not record["surfaces"]:
            lines.append("- None.")
        lines.extend(["", "### Current documentation"])
        lines.extend(_render_paths(record["documents"]))
        lines.extend(["", "### Owning specifications"])
        lines.extend(_render_paths(record["specifications"]))
        lines.extend(["", "### Implementation"])
        lines.extend(_render_paths(record["implementation"]))
        lines.extend(["", "### Verification"])
        lines.extend(_render_paths(record["verification"]))
        lines.extend(["", "### Notes / current limits", "", record["notes"] or "None."])
    return "\n".join(lines) + "\n"


def check(root: Path, *, write: bool = False) -> None:
    """Validate the registry and verify or refresh its generated reference."""
    try:
        root = root.resolve(strict=True)
    except OSError as error:
        raise DocumentationValidationError(
            [f"repository root is unavailable: {root} ({error})"]
        ) from error
    if not root.is_dir():
        raise DocumentationValidationError([f"repository root is not a directory: {root}"])
    registry, errors = _load_registry(root)
    if registry is None:
        raise DocumentationValidationError(errors)
    records, validation_errors = _validate_registry(
        root,
        registry,
        allow_generated_reference_missing=write,
    )
    errors.extend(validation_errors)
    if errors:
        raise DocumentationValidationError(errors)

    reference = str(registry["generated_reference"])
    expected = render(records)
    target_errors: list[str] = []
    generated = _safe_relative_path(root, reference, target_errors)
    if target_errors or generated is None:
        raise DocumentationValidationError(target_errors)
    if write:
        try:
            generated.parent.mkdir(parents=True, exist_ok=True)
            generated.write_text(expected, encoding="utf-8")
        except OSError as error:
            raise DocumentationValidationError(
                [f"generated reference could not be written: {reference} ({error})"]
            ) from error
        _records, post_write_errors = _validate_registry(
            root,
            registry,
            allow_generated_reference_missing=False,
        )
        if post_write_errors:
            raise DocumentationValidationError(post_write_errors)
    try:
        actual = generated.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        raise DocumentationValidationError(
            [f"generated reference is unreadable: {reference} ({error})"]
        )
    if actual != expected:
        raise DocumentationValidationError([f"generated reference is stale: {reference}"])


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=DEFAULT_ROOT, help="repository root to inspect"
    )
    parser.add_argument("--write", action="store_true", help="rewrite the generated reference")
    return parser


def main(arguments: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(arguments)
    try:
        check(args.root, write=args.write)
    except DocumentationValidationError as error:
        print("documentation validation failed:", file=sys.stderr)
        for item in error.errors:
            print(f"- {item}", file=sys.stderr)
        return 1
    print("documentation validation passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
